name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Важно: даём права на запись
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: 
        npm install webpack webpack-cli webpack-dev-server --save-dev
        npm install @babel/core babel-loader @babel/preset-env @babel/preset-react --save-dev
        npm install html-webpack-plugin clean-webpack-plugin --save-dev
        npm install react react-dom
        npm install style-loader css-loader --save-dev
        npm install react react-dom
        npm install @types/react @types/react-dom --save-dev
        npm install react-router-dom
        npm install html-webpack-plugin
        npm install --save-dev copy-webpack-plugin
        npm install --save-dev mini-css-extract-plugin
        npm install gh-pages --save-dev
      
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production
      
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        keep_files: false
        force_orphan: true
