name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
#    - name: Lint code
#      run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: install-and-test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # Добавьте это
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        keep_files: false
        force_orphan: true
